### ISSUE TITLE
timeoutError

### ISSUE THREAD

**Issue by Halo1211** [ndbiaw/anchira-watcher-downloader#2]
<img width="844" alt="image" src="https://github.com/ndbiaw/anchira-watcher-downloader/assets/42713232/3cc2bbcb-6c2f-47fc-9aa2-5d06a304d05a">
E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:60
            this.#timeoutError = new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: Waiting for selector `article` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:60:34)
    at IsolatedWorld.waitForFunction (E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Realm.js:35:26)
    at PQueryHandler.waitFor (E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\common\QueryHandler.js:180:95)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpFrame.waitForSelector (E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:511:21)
    at async CdpPage.waitForSelector (E:\Anchira\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:1483:20)
    at async scrapePage (E:\Anchira\build.js:5:3)
    at async scrapeSite (E:\Anchira\build.js:28:5)

how to fix this

**Comment by nayumiDEV** [comment]
Hi, due to recent changes you will need to take manual action to download the manga, unless you are willing to spend money to use noCaptcha services. I will update soon.
